name: "S3 sync & Cache invalidation"

on:
  push:
    branches: [ main ]
    paths:
      - 'Website/**.js'
      - 'Website/**.html'
      - 'Website/**.css'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  website:
    name: "S3 sync & Cloudfront cache invalidation"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./Website
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v3
      - name: Sync website folder to S3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          

